SEG491X-W2023-T42/mikado-machine

mikado-app/package-lock.json, mikado-app/package.json, mikado-app/src/App.js, mikado-app/src/context/FirebaseContext.js, mikado-app/src/firebase.js, mikado-app/src/index.js, mikado-app/src/pages/Graph.js, mikado-app/src/pages/SignIn.js
+ Added routing for authentication
+ Added authentication rules in firebase, so that no one can yoink our key and do weird stuff to it (need to be signed in!)
+ Added sign in page (very bare bones)
+ Added auth through google
=> Setup firebase auth

mikado-app/src/pages/Graph.js
+ Add arrows to connections & increased connection visibility
=> Changed connection arrow + styling

mikado-app/package-lock.json, mikado-app/package.json, mikado-app/src/pages/Graph.js
+ Added toast message for successful save for user feedback
+ Added error message on unsuccessful save for user feedback 
+ Added error logging for developers
=> Add toast message on successful graph save

mikado-app/.eslintrc.json, mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/pages/Graph/Overlay.js, mikado-app/src/pages/Graph/Overlays/FAB.js, mikado-app/src/pages/Graph/Overlays/FABSnackbar.js, mikado-app/src/pages/Graph/Overlays/Overlay.js, mikado-app/src/pages/Graph/Plaza.js, mikado-app/src/viewmodel/displayLayerStore.js
- Added FAB
- Vanished drawer
- Nodes now are added dynamically by looking for the next best free space (slow algo)
- Toast on successful/unsuccessful node add
=> 56 add a add node fab

mikado-app/.eslintrc.json, mikado-app/src/pages/Graph/MyDrawer.js, mikado-app/src/pages/Graph/Plaza.js
- Adds back drawer
- Adds opening/close functionality on desktop on selection/click away
- Changes text field to more closely align with design (ref was just being weird)
=> 69 add back the bottom panel and animate it down

mikado-app/.eslintrc.json, mikado-app/src/components/AppMenu.js, mikado-app/src/components/CustomControl/CustomControl.js, mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/pages/Graph/DisplayLayerHandle.js, mikado-app/src/pages/Graph/MyDrawer.js, mikado-app/src/pages/Graph/Plaza.js, mikado-app/src/viewmodel/displayLayerStore.js, mikado-app/src/viewmodel/serde.js
+ Add menu bar
+ Added profile picture with clickable menu (non-functional) 
+ Added graph title (static as of now)
+ Added logo (placeholder)
+ Add preliminary subgraph code
=> add app bar + prelim subgraph code

mikado-app/src/firebase.js, mikado-app/src/pages/Graph/CompleteNode.js, mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/pages/Graph/GoalNode.js, mikado-app/src/pages/Graph/LockedNode.js, mikado-app/src/pages/Graph/MyNode.js, mikado-app/src/pages/Graph/Plaza.css, mikado-app/src/pages/Graph/ReadyNode.js, mikado-app/src/pages/Graph/graphTheme.js, mikado-app/src/viewmodel/displayLayerStore.js, mikado-app/src/viewmodel/displayObjectFactory.js, mikado-app/src/viewmodel/serde.js
+ Add node typing
+ Add styling for each node type
+ Type persistence in DB
=> 105 add node types

mikado-app/src/pages/Graph/CompleteNode.js, mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/pages/Graph/LockedNode.js, mikado-app/src/pages/Graph/ReadyNode.js, mikado-app/src/viewmodel/displayLayerStore.js
+ Add completeion status
+ Typing now properly changes on connections and deletions
=> 59 persist the node completion status

mikado-app/src/pages/Graph/ReadyNode.js
=> fix (112): changed leaf node icon to be grass

mikado-app/src/pages/Graph/Plaza.css
Attempt to fix how Chrome Android is still trying to zoom on mobile.
=> fix: Double click actions on mobile

mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/pages/Graph/Plaza.css
Version of #133 covering more cases after debugging.
=> fix: double click actions mobile actually

mikado-app/src/helpers/NodeConstants.js, mikado-app/src/pages/Graph/DisplayLayer.js, mikado-app/src/viewmodel/DebugModifyNodePositions.java, mikado-app/src/viewmodel/collisionDetection.js, mikado-app/src/viewmodel/displayLayerStore.js
Fixes #144
Fixes #76
https://github.com/SEG491X-W2023-T42/mikado-machine/assets/25646384/893dc8c9-bacc-43c2-9229-611cb4967a70
=> fix (#144): Don't give up placing nodes nearer

mikado-app/src/pages/Graph/Plaza.css
=> feat (#153): added toolbar button microinteractions

firebase/firestore.rules, mikado-app/src/pages/Graph/Plaza.js, mikado-app/src/viewmodel/gatekeeper.js, mikado-app/src/viewmodel/serde.js
This feature allows admins like me (soon us) to impersonate other users like the uOttawa COOP office / Facebook has a feature for them to impersonate students. The immediate need for this is for me to upload the client's drawings to his account.
This also fixes some bugs in the persistence layer.
=> feat: Impersonate

mikado-app/public/LICENSE.txt
Welcome and hand permissions over to the new TA for the semester: Parva Satyaprakash Pathak.
=> feat: Welcome Parva!

mikado-app/src/graph/components/overlays/QuestOverlay.css, mikado-app/src/graph/components/overlays/QuestOverlay.js, mikado-app/src/graphlayer/component/GraphLayerViewer.js, mikado-app/src/graphlayer/store/GraphLayerViewerStore.js
Displays the current task you should work on. Can complete task from the UI, and displays next task after completion.
=> feat: current task overlay

mikado-app/src/graph/components/CustomControl.js, mikado-app/src/graphlayer/component/GraphLayerViewer.js, mikado-app/src/graphlayer/store/GraphLayerViewerStore.js
+ Autosave every 15 seconds if there has been any changes (does not autosave if no changes occured)
- Remove save icon in control bar
=> feat: autosave

mikado-app/src/graphlayer/component/GraphLayerViewer.js
=> fix: Pan not zoom on scroll

mikado-app/src/graphlayer/store/GraphLayerViewerStore.js, mikado-app/src/helpers/Api.js
All nodes that are children of a subgraph bieng created now are moved into the subgraph itself
=> feat: move all nodes under subgraph into subgraph

firebase/firebase.json, mikado-app/src/Firebase.js, mikado-app/src/context/FirebaseContext.js, mikado-app/src/graphlayer/component/GraphLayerViewer.js, mikado-app/src/graphlayer/component/NodeSerializer.js, mikado-app/src/graphlayer/store/Gatekeeper.js, mikado-app/src/graphlayer/store/GraphLayerViewerStore.js
=> feat: Copy and paste
